version: "3"

services:
  flask_dev_tests:
    build:
        context: .
        dockerfile: Dockerfile.tests
    container_name: flask_dev_tests
    volumes:
      - "./tests:/tests"
      - "./app:/tests/app"
      - "./.vscode:/.vscode"
    environment:
      TZ: "Europe/London"
    command: tail -F anything  # keeps the container running
