use local_db;

CREATE TABLE users (
    id int NOT NULL AUTO_INCREMENT,
    un VARCHAR(255) NOT NULL,
    pw VARCHAR(255) NOT NULL,
    salt VARCHAR(255) NOT NULL,
    creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
