use local_db;

CREATE TABLE temp_data (
    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    temp FLOAT NOT NULL,
    error BOOLEAN NOT NULL,
    loc VARCHAR(255) NOT NULL,
    update_date DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
